export const BEGIN_LOGIN = "BEGIN_LOGIN";
export const LOGIN = "LOGIN";
export const UPDATE_DATA_LOGIN = "UPDATE_DATA_LOGIN";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GOT_DATA_LOGIN = "GOT_DATA_LOGIN";
export const LOGOUT = "LOGOUT";
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const SKIP_LOGIN = "SKIP_LOGIN";
export const GET_DATA = "GET_DATA";

export const BEGIN_GET_DATA_PROFILE_USER = "BEGIN_GET_DATA_PROFILE_USER";
export const GET_DATA_PROFILE_USER_SUCCESS = "GET_DATA_PROFILE_USER_SUCCESS";
export const GET_DATA_PROFILE_USER_ERROR = "GET_DATA_PROFILE_USER_ERROR";

export const BEGIN_GET_DATA_SALER_PAID = "BEGIN_GET_DATA_SALER_PAID";
export const GET_DATA_SALER_PAID_SUCCESS = "GET_DATA_SALER_PAID_SUCCESS";
export const GET_DATA_SALER_PAID_ERROR = "GET_DATA_SALER_PAID_ERROR";

export const BEGIN_GET_DATA_SALER_CALL_HISTORY = "BEGIN_GET_DATA_SALER_CALL_HISTORY";
export const GET_DATA_SALER_CALL_HISTORY_SUCCESS = "GET_DATA_SALER_CALL_HISTORY_SUCCESS";
export const GET_DATA_SALER_CALL_HISTORY_ERROR = "GET_DATA_SALER_CALL_HISTORY_ERROR";

export const BEGIN_GET_DATA_USER_TRANSFORM_MONEY = "BEGIN_GET_DATA_USER_TRANSFORM_MONEY";
export const GET_DATA_USER_TRANSFORM_MONEY_SUCCESS = "GET_DATA_USER_TRANSFORM_MONEY_SUCCESS";
export const GET_DATA_USER_TRANSFORM_MONEY_ERROR = "GET_DATA_USER_TRANSFORM_MONEY_ERROR";

export const BEGIN_GET_DATA_WORK_SHIFT_HISTORY = "BEGIN_GET_DATA_WORK_SHIFT_HISTORY";
export const GET_DATA_WORK_SHIFT_HISTORY_SUCCESS = "GET_DATA_WORK_SHIFT_HISTORY_SUCCESS";
export const GET_DATA_WORK_SHIFT_HISTORY_ERROR = "GET_DATA_WORK_SHIFT_HISTORY_ERROR";

export const BEGIN_GET_DATA_REGISTER_SHIFT_HISTORY = "BEGIN_GET_DATA_REGISTER_SHIFT_HISTORY";
export const GET_DATA_REGISTER_SHIFT_HISTORY_SUCCESS = "GET_DATA_REGISTER_SHIFT_HISTORY_SUCCESS";
export const GET_DATA_REGISTER_SHIFT_HISTORY_ERROR = "GET_DATA_REGISTER_SHIFT_HISTORY_ERROR";

export const BEGIN_GET_DATA_USER_CLASSES = "BEGIN_GET_DATA_USER_CLASSES";
export const GET_DATA_USER_CLASSES_SUCCESS = "GET_DATA_USER_CLASSES_SUCCESS";
export const GET_DATA_USER_CLASSES_ERROR = "GET_DATA_USER_CLASSES_ERROR";

export const RESET_DATA_URL = "RESET_DATA_URL";

export const BEGIN_GET_DATA_GEN = "BEGIN_GET_DATA_GEN";
export const GET_DATA_GEN_SUCCESS = "GET_DATA_GEN_SUCCESS";
export const GET_DATA_GEN_ERROR = "GET_DATA_GEN_ERROR";
export const BEGIN_GET_DATA_ROLE = "BEGIN_GET_DATA_ROLE";
export const GET_DATA_ROLE_SUCCESS = "GET_DATA_ROLE_SUCCESS";
export const GET_DATA_ROLE_ERROR = "GET_DATA_ROLE_ERROR";
export const BEGIN_GET_DATA_OVERVIEW = "BEGIN_GET_DATA_OVERVIEW";
export const GET_DATA_OVERVIEW_SUCCESS = "GET_DATA_OVERVIEW_SUCCESS";
export const GET_DATA_OVERVIEW_ERROR = "GET_DATA_OVERVIEW_ERROR";
export const BEGIN_REFRESH_OVERVIEW = "BEGIN_REFRESH_OVERVIEW";
export const REFRESH_OVERVIEW_SUCCESS = "REFRESH_OVERVIEW_SUCCESS";
export const REFRESH_OVERVIEW_ERROR = "REFRESH_OVERVIEW_ERROR";
export const BEGIN_GET_DATA_BASE = "BEGIN_GET_DATA_BASE";
export const GET_DATA_BASE_SUCCESS = "GET_DATA_BASE_SUCCESS";
export const GET_DATA_BASE_ERROR = "GET_DATA_BASE_ERROR";
export const BEGIN_REFRESH_BASE = "BEGIN_REFRESH_BASE";
export const REFRESH_BASE_SUCCESS = "REFRESH_BASE_SUCCESS";
export const REFRESH_BASE_ERROR = "REFRESH_BASE_ERROR";

export const BEGIN_GET_CLASS_LIST_CURRENT = "BEGIN_GET_CLASS_LIST_CURRENT";
export const GET_CLASS_LIST_CURRENT_SUCCESS = "GET_CLASS_LIST_CURRENT_SUCCESS";
export const BEGIN_REFRESH_CLASS_LIST_CURRENT = "BEGIN_REFRESH_CLASS_LIST_CURRENT";
export const REFRESH_CLASS_LIST_CURRENT_SUCCESS = "REFRESH_CLASS_LIST_CURRENT_SUCCESS";
export const REFRESH_CLASS_LIST_CURRENT_ERROR = "REFRESH_CLASS_LIST_CURRENT_ERROR";
export const GET_CLASS_LIST_CURRENT_ERROR = "GET_CLASS_LIST_CURRENT_ERROR";
export const BEGIN_GET_DETAIL_CLASS = "BEGIN_GET_DETAIL_CLASS";
export const GET_DETAIL_CLASS_SUCCESS = "GET_DETAIL_CLASS_SUCCESS";
// get student register
export const BEGIN_GET_STUDENT_REGISTER = "BEGIN_GET_STUDENT_REGISTER";
export const BEGIN_SEARCH_STUDENT_REGISTER = "BEGIN_SEARCH_STUDENT_REGISTER";
export const BEGIN_REFRESH_STUDENT_REGISTER = "BEGIN_REFRESH_STUDENT_REGISTER";
export const GET_STUDENT_REGISTER_SUCCESS = "GET_STUDENT_REGISTER_SUCCESS";
export const GET_STUDENT_REGISTER_ERROR = "GET_STUDENT_REGISTER_SUCCESS";

// refresh New

export const GET_REFRESH_SUCCESS = "GET_REFRESH_SUCCESS";
export const GET_REFRESH_ERROR = "GET_REFRESH_ERROR";
// detail blogs
export const BEGIN_GET_DETAIL_BLOG = "BEGIN_GET_DETAIL_BLOG";
export const GET_DETAIL_BLOG_SUCCESS = "GET_DETAIL_BLOG_SUCCESS";
// get blogs

export const BEGIN_GET_LIST_BLOG = "BEGIN_GET_LIST_BLOG";
export const BEGIN_SEARCH_LIST_BLOG = "BEGIN_SEARCH_LIST_BLOG";
export const BEGIN_REFRESH_LIST_BLOG = "BEGIN_REFRESH_LIST_BLOG";
export const GET_LIST_BLOG_SUCCESS = "GET_LIST_BLOG_SUCCESS";
export const GET_LIST_BLOG_ERROR = "GET_LIST_BLOG_ERROR";

//notification
export const BEGIN_GET_NOTIFICATION = "BEGIN_GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const BEGIN_REFRESH_NOTIFICATION = "BEGIN_REFRESH_NOTIFICATION";
export const FIRST_GET_NOTIFICATION = "FIRST_GET_NOTIFICATION";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";

//detail student
export const BEGIN_GET_DATA_DETAIL_STUDENT = "BEGIN_GET_DATA_DETAIL_STUDENT";
export const GET_DATA_DETAIL_STUDENT_SUCCESS = "GET_DATA_DETAIL_STUDENT_SUCCESS";
export const GET_DATA_DETAIL_STUDENT_ERROR = "GET_DATA_DETAIL_STUDENT_ERROR";

//regsiter of student
export const BEGIN_GET_DATA_REGISTER_STUDENT = "BEGIN_GET_DATA_REGISTER_STUDENT";
export const GET_DATA_REGISTER_STUDENT_SUCCESS = "GET_DATA_REGISTER_STUDENT_SUCCESS";
export const GET_DATA_REGISTER_STUDENT_ERROR = "GET_DATA_REGISTER_STUDENT_ERROR";

//call of student
export const BEGIN_GET_DATA_CALL_STUDENT = "BEGIN_GET_DATA_CALL_STUDENT";
export const GET_DATA_CALL_STUDENT_SUCCESS = "GET_DATA_CALL_STUDENT_SUCCESS";
export const GET_DATA_CALL_STUDENT_ERROR = "GET_DATA_CALL_STUDENT_ERROR";

// get subjects
export const BEGIN_GET_LIST_SUBJECT = "BEGIN_GET_LIST_SUBJECT";
export const BEGIN_REFRESH_LIST_SUBJECT = "BEGIN_REFRESH_LIST_SUBJECT";
export const BEGIN_SEARCH_LIST_STUDENT = "BEGIN_SEARCH_LIST_STUDENT";
export const GET_LIST_SUBJECT_SUCCESS = "GET_LIST_SUBJECT_SUCCESS";
export const GET_LIST_SUBJECT_ERROR = "GET_LIST_SUBJECT_ERROR";

export const BEGIN_GET_DIRECT_SHIFT = "BEGIN_GET_DIRECT_SHIFT";
export const GET_DIRECT_SHIFT_SUCCESS = "GET_DIRECT_SHIFT_SUCCESS";
export const GET_DIRECT_SHIFT_ERROR = "GET_DIRECT_SHIFT_ERROR";
export const BEGIN_PUT_REGISTER_DIRECT_SHIFT = "BEGIN_PUT_REGISTER_DIRECT_SHIFT";
export const PUT_REGISTER_DIRECT_SHIFT_SUCCESS = "PUT_REGISTER_DIRECT_SHIFT_SUCCESS";
export const PUT_REGISTER_DIRECT_SHIFT_ERROR = "PUT_REGISTER_DIRECT_SHIFT_ERROR";
export const BEGIN_PUT_REMOVE_DIRECT_SHIFT = "BEGIN_PUT_REMOVE_DIRECT_SHIFT";
export const PUT_REMOVE_DIRECT_SHIFT_SUCCESS = "PUT_REMOVE_DIRECT_SHIFT_SUCCESS";
export const PUT_REMOVE_DIRECT_SHIFT_ERROR = "PUT_REMOVE_DIRECT_SHIFT_ERROR";


// get bases
export const BEGIN_GET_LIST_BASE = "BEGIN_GET_LIST_BASE";
export const GET_LIST_BASE_SUCCESS = "GET_LIST_BASE_SUCCESS";
export const GET_LIST_BASE_ERROR = "GET_LIST_BASE_ERROR";
// get more bases
export const BEGIN_GET_MORE_LIST_BASE = "BEGIN_GET_MORE_LIST_BASE";
export const GET_MORE_LIST_BASE_SUCCESS = "GET_MORE_LIST_BASE_SUCCESS";
// refresh bases
export const BEGIN_REFRESH_LIST_BASE = "BEGIN_REFRESH_LIST_BASE";
export const GET_REFRESH_BASE_SUCCESS = "GET_REFRESH_BASE_SUCCESS";
//
// get all bases
export const BEGIN_GET_ALL_LIST_BASE = "BEGIN_GET_ALL_LIST_BASE";
export const GET_ALL_LIST_BASE_SUCCESS = "GET_ALL_LIST_BASE_SUCCESS";

//get all provinces

export const BEGIN_GET_ALL_PROVINCES = "BEGIN_GET_ALL_PROVINCES";
export const GET_ALL_PROVINCES_SUCCESS = "GET_ALL_PROVINCES_SUCCESS";

// get emails
export const BEGIN_GET_LIST_EMAIL = "BEGIN_GET_LIST_EMAIL";
export const GET_LIST_EMAIL_SUCCESS = "GET_LIST_EMAIL_SUCCESS";
export const GET_LIST_EMAIL_ERROR = "GET_LIST_EMAIL_ERROR";
//get more emails
export const BEGIN_GET_MORE_LIST_EMAIL = "BEGIN_GET_MORE_LIST_EMAIL";
export const GET_MORE_LIST_EMAIL_SUCCESS = "GET_MORE_LIST_EMAIL_SUCCESS";
//refresh emails
export const BEGIN_REFRESH_LISH_EMAIL = "BEGIN_REFRESH_LISH_EMAIL";
export const GET_REFRESH_EMAIL_SUCCESS = "GET_REFRESH_EMAIL_SUCCESS";
//detail email
export const BEGIN_GET_DETAIL_EMAIL = "BEGIN_GET_DETAIL_EMAIL";
export const GET_DETAIL_EMAIL_SUCCESS = " GET_DETAIL_EMAIL_SUCCESS";
export const BEGIN_SEARCH_LIST_EMAIL = "BEGIN_SEARCH_LIST_EMAIL";

export const BEGIN_GET_DATA_ATTENDANCE_STUDENT = "BEGIN_GET_DATA_ATTENDANCE_STUDENT";
export const GET_DATA_ATTENDANCE_STUDENT_SUCCESS = "GET_DATA_ATTENDANCE_STUDENT_SUCCESS";
export const GET_DATA_ATTENDANCE_STUDENT_ERROR = "GET_DATA_ATTENDANCE_STUDENT_ERROR";




//staff
export const BEGIN_GET_LIST_STAFF = "BEGIN_GET_LIST_STAFF";
export const BEGIN_SEARCH_LIST_STAFF = "BEGIN_SEARCH_LIST_STAFF";
export const BEGIN_REFRESH_LIST_STAFF = "BEGIN_REFRESH_LIST_STAFF";
export const GET_LIST_STAFF_SUCCESS = "GET_LIST_STAFF_SUCCESS";
export const GET_LIST_STAFF_ERROR = "GET_LIST_STAFF_ERROR";


export const GET_REFRESH_STAFF_SUCCESS = "GET_REFRESH_STAFF_SUCCESS";
// get department
export const BEGIN_GET_LIST_DEPARTMENT = "BEGIN_GET_LIST_DEPARTMENT";
export const GET_LIST_DEPARTMENT_SUCCESS = "GET_LIST_DEPARTMENT_SUCCESS";
// get more department
export const BEGIN_GET_MORE_LIST_DEPARTMENT = "BEGIN_GET_MORE_LIST_DEPARTMENT";
export const GET_MORE_LIST_DEPARTMENT_SUCCESS = "GET_MORE_LIST_DEPARTMENT_SUCCESS";
// refresh department
export const BEGIN_REFRESH_LIST_DEPARTMENT = "BEGIN_REFRESH_LIST_DEPARTMENT";
export const GET_REFRESH_DEPARTMENT_SUCCESS = "GET_REFRESH_DEPARTMENT_SUCCESS";
// get all department
export const BEGIN_GET_ALL_LIST_DEPARTMENT = "BEGIN_GET_ALL_LIST_DEPARTMENT";
export const GET_ALL_LIST_DEPARTMENT_SUCCESS = "GET_ALL_LIST_DEPARTMENT_SUCCESS";

// get user collect money
export const BEGIN_GET_LIST_USER_COLLECT = "BEGIN_GET_LIST_USER_COLLECT";
export const GET_LIST_USER_COLLECT_SUCCESS = "GET_LIST_USER_COLLECT_SUCCESS";

// update collect money 
export const BEGIN_COLLECT_MONEY = "BEGIN_COLLECT_MONEY";
export const UPDATE_COLLECT_MONEY_SUCCESS = "UPDATE_COLLECT_MONEY_SUCCESS";
export const UPDATE_COLLECT_MONEY_ERROR = "UPDATE_COLLECT_MONEY_ERROR";
// refresh user collect 

export const BEGIN_REFRESH_LIST_USER_COLLECT = "BEGIN_REFRESH_LIST_USER_COLLECT";
export const REFRESH_LIST_USER_COLLECT_SUCCESS = "REFRESH_LIST_USER_COLLECT_SUCCESS";

// paid student
export const BEGIN_GET_PAID_STUDENT = "BEGIN_GET_PAID_STUDENT";
export const GET_PAID_STUDENT_SUCCESS = "GET_PAID_STUDENT_SUCCESS";
export const GET_PAID_STUDENT_ERROR = "GET_PAID_STUDENT_ERROR";
export const BEGIN_REFRESH_PAID_STUDENT = "BEGIN_REFRESH_PAID_STUDENT";
export const REFRESH_PAID_STUDENT_SUCCESS = "REFRESH_PAID_STUDENT_SUCCESS";
export const REFRESH_PAID_STUDENT_ERROR = "REFRESH_PAID_STUDENT_ERROR";
export const BEGIN_GET_MORE_PAID_STUDENT = "BEGIN_GET_MORE_PAID_STUDENT";
export const GET_MORE_PAID_STUDENT_SUCCESS = "GET_MORE_PAID_STUDENT_SUCCESS";
export const GET_MORE_PAID_STUDENT_ERROR = "GET_MORE_PAID_STUDENT_ERROR";
// work shift
export const BEGIN_GET_WORK_SHIFT = "BEGIN_GET_WORK_SHIFT";
export const GET_WORK_SHIFT_SUCCESS = "GET_WORK_SHIFT_SUCCESS";
export const GET_WORK_SHIFT_ERROR = "GET_WORK_SHIFT_ERROR";
export const BEGIN_REFRESH_WORK_SHIFT = "BEGIN_REFRESH_WORK_SHIFT";
export const REFRESH_WORK_SHIFT_SUCCESS = "REFRESH_WORK_SHIFT_SUCCESS";
export const REFRESH_WORK_SHIFT_ERROR = "REFRESH_WORK_SHIFT_ERROR";
export const BEGIN_PUT_REGISTER_WORK_SHIFT = "BEGIN_PUT_REGISTER_WORK_SHIFT";
export const PUT_REGISTER_WORK_SHIFT_SUCCESS = "PUT_REGISTER_WORK_SHIFT_SUCCESS";
export const PUT_REGISTER_WORK_SHIFT_ERROR = "PUT_REGISTER_WORK_SHIFT_ERROR";
export const BEGIN_PUT_REMOVE_WORK_SHIFT = "BEGIN_PUT_REMOVE_WORK_SHIFT";
export const PUT_REMOVE_WORK_SHIFT_SUCCESS = "PUT_REMOVE_WORK_SHIFT_SUCCESS";
export const PUT_REMOVE_WORK_SHIFT_ERROR = "PUT_REMOVE_WORK_SHIFT_ERROR";

//WORK calender

export const BEGIN_GET_WORK_CALENDAR = "BEGIN_GET_WORK_CALENDAR";
export const GET_WORK_CALENDAR_SUCCESS = "GET_WORK_CALENDAR_SUCCESS";
export const GET_WORK_CALENDAR_ERROR = "GET_WORK_CALENDAR_ERROR";
export const BEGIN_REFRESH_CALENDAR_SHIFT = "BEGIN_REFRESH_WORK_CALENDAR";
export const REFRESH_WORK_CALENDAR_SUCCESS = "REFRESH_WORK_CALENDAR_SUCCESS";
export const REFRESH_WORK_CALENDAR_ERROR = "REFRESH_WORK_CALENDAR_ERROR";
export const BEGIN_PUT_REGISTER_WORK_CALENDAR = "BEGIN_PUT_REGISTER_WORK_CALENDAR";
export const PUT_REGISTER_WORK_CALENDAR_SUCCESS = "PUT_REGISTER_WORK_CALENDAR_SUCCESS";
export const PUT_REGISTER_WORK_CALENDAR_ERROR = "PUT_REGISTER_WORK_CALENDAR_ERROR";
export const BEGIN_PUT_REMOVE_WORK_CALENDAR = "BEGIN_PUT_REMOVE_WORK_CALENDAR";
export const PUT_REMOVE_WORK_CALENDAR_SUCCESS = "PUT_REMOVE_WORK_CALENDAR_SUCCESS";
export const PUT_REMOVE_WORK_CALENDAR_ERROR = "PUT_REMOVE_WORK_CALENDAR_ERROR";

// checkin 
export const BEGIN_CHECK_IN = 'BEGIN_CHECK_IN';
export const CHECK_IN_SUCCESS = 'CHECK_IN_SUCCESS';
export const CHECK_IN_ERROR = 'CHECK_IN_ERROR';

// history checkin
export const BEGIN_GET_LIST_HISTORY_CHECKIN = "BEGIN_GET_LIST_HISTORY_CHECKIN";
export const GET_LIST_HISTORY_CHECKIN_SUCCESS = "GET_LIST_HISTORY_CHECKIN_SUCCESS";

export const BEGIN_GET_MORE_LIST_HISTORY_CHECKIN = "BEGIN_GET_MORE_LIST_HISTORY_CHECKIN";
export const GET_MORE_LIST_HISTORY_CHECKIN_SUCCESS = "GET_MORE_LIST_HISTORY_CHECKIN_SUCCESS";

export const BEGIN_REFRESH_LIST_HISTORY_CHECKIN = "BEGIN_REFRESH_LIST_HISTORY_CHECKIN";
export const GET_REFRESH_HISTORY_CHECKIN_SUCCESS = "GET_REFRESH_HISTORY_CHECKIN_SUCCESS";


// quét QR 
export const BEGIN_SCAN_QR_CODE = "BEGIN_SCAN_QR_CODE";
export const IS_SCANNED_QR_CODE = "IS_SCANNED_QR_CODE";
// attendance Student 
export const BEGIN_GET_INFOR_STUDENT = "BEGIN_GET_INFOR_STUDENT";
export const LOAD_GET_INFOR_STUDENT_SUCCESSFUL = "LOAD_GET_INFOR_STUDENT_SUCCESSFUL";
export const LOAD_GET_INFOR_STUDENT_ERROR = "LOAD_GET_INFOR_STUDENT_ERROR";
export const BEGIN_POST_ATTENDANCE_STUDENT = "BEGIN_POST_ATTENDANCE_STUDENT";
export const LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL = "LOAD_POST_ATTENDANCE_STUDENT_SUCCESSFUL";
export const LOAD_POST_ATTENDANCE_STUDENT_ERROR = "LOAD_POST_ATTENDANCE_STUDENT_ERROR";
export const SELECT_BUTTON_ENTER_STUDENT_CODE = "SELECT_BUTTON_ENTER_STUDENT_CODE";
export const SCANNED_QR_CODE = "SCANNED_QR_CODE";
export const ATTEND_CURRENT_CLASS_STUDY = "ATTEND_CURRENT_CLASS_STUDY"



// support 
export const BEGIN_FEEDBACK = "BEGIN_FEEDBACK";
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_ERROR = "FEEDBACK_ERROR";
export const UPLOAD_IMAGE_SUPPORT = "UPLOAD_IMAGE_SUPPORT";

//
export const BEGIN_DATA_HISTORY_TRANSACTION_LOAD = 'BEGIN_DATA_HISTORY_TRANSACTION_LOAD';
export const BEGIN_DATA_HISTORY_TRANSACTION_REFRESH = 'BEGIN_DATA_HISTORY_TRANSACTION_REFRESH';
export const BEGIN_DATA_HISTORY_TRANSACTION_SEARCH = 'BEGIN_DATA_HISTORY_TRANSACTION_SEARCH';

export const LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL = 'LOAD_DATA_HISTORY_TRANSACTION_SUCCESSFUL';
export const LOAD_DATA_HISTORY_TRANSACTION_ERROR = 'LOAD_DATA_HISTORY_TRANSACTION_ERROR';
export const BEGIN_TRANSACTION = 'BEGIN_TRANSACTION';
export const TRANSACTION_SUCCESSFUL = 'TRANSACTION_SUCCESSFUL';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const BEGIN_CONFIRM_TRANSACTION = 'BEGIN_CONFIRM_TRANSACTION';
export const CONFIRM_TRANSACTION_SUCCESSFUL = 'CONFIRM_TRANSACTION_SUCCESSFUL';
export const CONFIRM_TRANSACTION_ERROR = 'CONFIRM_TRANSACTION_ERROR';
export const CHANGE_STATUS_TRANSACTION = 'CHANGE_STATUS_TRANSACTION';
export const UPDATE_HISTORY_TRANSACTION_SOCKET = 'UPDATE_HISTORY_TRANSACTION_SOCKET';


//class-room base
export const BEGIN_GET_LIST_CLASS_ROOM = "BEGIN_GET_LIST_CLASS_ROOM";
export const GET_LIST_CLASS_ROOM_SUCCESS = "GET_LIST_CLASS_ROOM_SUCCESS";
export const GET_LIST_CLASS_ROOM_ERROR = "GET_LIST_CLASS_ROOM_ERROR";
// get more _CLASS_ROOM
export const BEGIN_GET_MORE_LIST_CLASS_ROOM = "BEGIN_GET_MORE_LIST_CLASS_ROOM";
export const GET_MORE_LIST_CLASS_ROOM_SUCCESS = "GET_MORE_LIST_CLASS_ROOM_SUCCESS";
// refresh _CLASS_ROOM
export const BEGIN_REFRESH_LIST_CLASS_ROOM = "BEGIN_REFRESH_LIST_CLASS_ROOM";
export const GET_REFRESH_CLASS_ROOM_SUCCESS = "GET_REFRESH_CLASS_ROOM_SUCCESS";
//
// get all _CLASS_ROOM
export const BEGIN_GET_ALL_LIST_CLASS_ROOM = "BEGIN_GET_ALL_LIST_CLASS_ROOM";
export const GET_ALL_LIST_CLASS_ROOM_SUCCESS = "GET_ALL_LIST_CLASS_ROOM_SUCCESS";
//search
export const BEGIN_SEARCH_LIST_CLASS_ROOM = "BEGIN_SEARCH_LIST_CLASSROOM";
// detail classroom
export const BEGIN_GET_LIST_CLASS_ROOM_DETAIL = "BEGIN_GET_LIST_CLASS_ROOM_DETAIL";
export const GET_LIST_CLASS_ROOM_DETAIL_SUCCESS = "GET_LIST_CLASS_ROOM_DETAIL_SUCCESS";
export const GET_LIST_CLASS_ROOM_DETAIL_ERROR = "GET_LIST_CLASS_ROOM_DETAIL_ERROR";

// worktime history
export const BEGIN_GET_LIST_WORKTIME_HISTORY = "BEGIN_GET_LIST_WORKTIME_HISTORY";
export const GET_LIST_WORKTIME_HISTORY_SUCCESS = "GET_LIST_WORKTIME_HISTORY_SUCCESS";
export const GET_LIST_WORKTIME_HISTORY_ERROR = "GET_LIST_WORKTIME_HISTORY_ERROR";
export const BEGIN_REFRESH_LIST_WORKTIME_HISTORY = "BEGIN_REFRESH_LIST_WORKTIME_HISTORY";
export const GET_REFRESH_LIST_WORKTIME_SUCCESS = "GET_REFRESH_LIST_WORKTIME_SUCCESS";
export const BEGIN_GET_LIST_CLASS_ROOM_FROM_BASE = "BEGIN_GET_LIST_CLASS_ROOM_FROM_BASE";

// history shift register
export const BEGIN_GET_LIST_HISTORY_SHIFT_REGISTER = "BEGIN_GET_LIST_HISTORY_SHIFT_REGISTER";
export const GET_LIST_HISTORY_SHIFT_REGISTER_SUCCESS = "GET_LIST_HISTORY_SHIFT_REGISTER_SUCCESS";
export const GET_LIST_HISTORY_SHIFT_REGISTER_ERROR = "GET_LIST_HISTORY_SHIFT_REGISTER_ERROR";
export const BEGIN_REFRESH_LIST_HISTORY_SHIFT_REGISTER = "BEGIN_REFRESH_LIST_HISTORY_SHIFT_REGISTER";
export const GET_REFRESH_LIST_HISTORY_SHIFT_REGISTER_SUCCESS = "GET_REFRESH_LIST_HISTORY_SHIFT_REGISTER_SUCCESS";


// expenditure 

export const BEGIN_DATA_HISTORY_EXPENDITURE_REFRESH = "BEGIN_DATA_HISTORY_EXPENDITURE_REFRESH";
export const BEGIN_DATA_HISTORY_EXPENDITURE_SEARCH = "BEGIN_DATA_HISTORY_EXPENDITURE_SEARCH";
export const BEGIN_DATA_HISTORY_EXPENDITURE_LOAD = "BEGIN_DATA_HISTORY_EXPENDITURE_LOAD";
export const LOAD_DATA_HISTORY_EXPENDITURE_ERROR = "LOAD_DATA_HISTORY_EXPENDITURE_ERROR";
export const LOAD_DATA_HISTORY_EXPENDITURE_SUCCESSFUL = "LOAD_DATA_HISTORY_EXPENDITURE_SUCCESSFUL";
export const BEGIN_EXPENDITURE = "BEGIN_EXPENDITURE";
export const EXPENDITURE_SUCCESSFUL = "EXPENDITURE_SUCCESSFUL";
export const EXPENDITURE_ERROR = "EXPENDITURE_SUCCESSFUL";
export const BEGIN_GET_CATEGORY = "BEGIN_GET_CATEGORY";
export const GET_CATEGORY_EXPENDITURE_SUCCESS = "GET_CATEGORY_EXPENDITURE_SUCCESS";
export const GET_CATEGORY_EXPENDITURE_ERROR = "GET_CATEGORY_EXPENDITURE_ERROR";
export const BEGIN_GET_USER_EXPENDITURE = "BEGIN_GET_USER_EXPENDITURE";
export const GET_USER_EXPENDITURE_SUCCESS = "GET_USER_EXPENDITURE_SUCCESS";
export const GET_USER_EXPENDITURE_ERROR = "GET_USER_EXPENDITURE_ERROR";
// class start date
export const BEGIN_GET_LIST_CLASS_START_DATE = "BEGIN_GET_LIST_CLASS_START_DATE";
export const GET_LIST_CLASS_START_DATE_SUCCESS = "GET_LIST_CLASS_START_DATE_SUCCESS";
export const GET_LIST_CLASS_START_DATE_ERROR = "GET_LIST_CLASS_START_DATE_ERROR";
export const BEGIN_REFRESH_LIST_CLASS_START_DATE = "BEGIN_REFRESH_LIST_HISTORY_SHIFT_REGISTER";
export const GET_REFRESH_LIST_CLASS_START_DATE_SUCCESS = "GET_REFRESH_LIST_HISTORY_SHIFT_REGISTER_SUCCESS";
export const BEGIN_SEARCH_LIST_CLASS_START_DATE = "BEGIN_SEARCH_LIST_CLASS_START_DATE";
export const BEGIN_GET_ALL_SUBJECT = "BEGIN_GET_ALL_SUBJECT";
export const GET_ALL_SUBJECT_SUCCESS = "GET_ALL_SUBJECT_SUCCESS";
export const GET_ALL_SUBJECT_ERROR = "GET_ALL_SUBJECT_ERROR";


//student in class 
export const BEGIN_GET_LIST_STUDENT_IN_CLASS = "BEGIN_GET_LIST_STUDENT_IN_CLASS ";
export const GET_LIST_STUDENT_IN_CLASS_SUCCESS = "GET_LIST_STUDENT_IN_CLASS_SUCCESS ";
export const GET_LIST_STUDENT_IN_ERROR = "GET_LIST_STUDENT_IN_ERROR ";
// staff keep money transaction

export const BEGIN_DATA_STAFF_TRANSACTION_LOAD = 'BEGIN_DATA_STAFF_TRANSACTION_LOAD';
export const BEGIN_DATA_STAFF_TRANSACTION_REFRESH = 'BEGIN_DATA_STAFF_TRANSACTION_REFRESH';
export const BEGIN_DATA_STAFF_TRANSACTION_SEARCH = 'BEGIN_DATA_STAFF_TRANSACTION_SEARCH';
export const LOAD_DATA_STAFF_TRANSACTION_SUCCESSFUL = 'LOAD_DATA_STAFF_TRANSACTION_SUCCESSFUL';
export const LOAD_DATA_STAFF_TRANSACTION_ERROR = 'LOAD_DATA_STAFF_TRANSACTION_ERROR';
// list staff keep money 
export const BEGIN_DATA_STAFF_KEEP_MONEY_LOAD = 'BEGIN_DATA_STAFF_KEEP_MONEY_LOAD';
export const BEGIN_DATA_STAFF_KEEP_MONEY_REFRESH = 'BEGIN_DATA_STAFF_KEEP_MONEY_REFRESH';
export const BEGIN_DATA_STAFF_KEEP_MONEY_SEARCH = 'BEGIN_DATA_STAFF_KEEP_MONEY_SEARCH';
export const LOAD_DATA_STAFF_KEEP_MONEY_SUCCESSFUL = 'LOAD_DATA_STAFF_KEEP_MONEY_SUCCESSFUL';
export const LOAD_DATA_STAFF_KEEP_MONEY_ERROR = 'LOAD_DATA_STAFF_KEEP_MONEY_ERROR';

// finance transaction 
export const BEGIN_DATA_FINANCE_TRANSACTION_LOAD = 'BEGIN_DATA_FINANCE_TRANSACTION_LOAD';
export const BEGIN_DATA_FINANCE_TRANSACTION_REFRESH = 'BEGIN_DATA_FINANCE_TRANSACTION_REFRESH';
export const BEGIN_DATA_FINANCE_TRANSACTION_SEARCH = 'BEGIN_DATA_FINANCE_TRANSACTION_SEARCH';
export const LOAD_DATA_FINANCE_TRANSACTION_SUCCESSFUL = 'LOAD_DATA_FINANCE_TRANSACTION_SUCCESSFUL';
export const LOAD_DATA_FINANCE_TRANSACTION_ERROR = 'LOAD_DATA_FINANCE_TRANSACTION_ERROR';
// finance summary
export const BEGIN_DATA_FINANCE_SUMMARY_LOAD = 'BEGIN_DATA_FINANCE_SUMMARY_LOAD';
export const LOAD_DATA_FINANCE_SUMMARY_SUCCESSFUL = 'LOAD_DATA_FINANCE_SUMMARY_SUCCESSFUL';
export const LOAD_DATA_FINANCE_SUMMARY_ERROR = 'LOAD_DATA_FINANCE_SUMMARY_ERROR';

//tabs permission
export const BEGIN_LOAD_TABS = "BEGIN_LOAD_TABS";
export const LOAD_TABS_SUCCESS = "LOAD_TABS_SUCCESS";
export const LOAD_TABS_ERROR = "LOAD_TABS_ERROR";
