export const STRINGS = {
    LOGO_COLOR: 'color',
    LOGO_ME: 'ME',
    REGISTER: 'Register',
    NAME: 'Name',
    EMAIL: 'Email',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    LOGIN: 'Đăng nhập',
    PROGRAM: 'Lập trình',
    DESIGN: 'Thiết kế',
    NOT_CONNTECT_NETWORK: 'Không có kết nối mạng',
    SETTING: 'Cài đặt',
    TRY_AGAIN: 'Thử lại',
    OUT: 'Thoát',
    LOGIN_ERROR: 'Đăng nhập thất bại',
    MESSAGE_LOGIN_ERROR: 'Vui lòng kiểm tra lại thông tin tài khoản',
    HAVE_ERROR: 'Có lỗi xảy ra',
    EMPTY_NAME: 'Bạn chưa nhập tên',
    EMPTY_USERNAME: 'Bạn chưa nhập tên tài khoản',
    EMPTY_PASSWORD: 'Bạn chưa nhập mật khẩu',
    EMPTY_EMAIL: 'Bạn chưa nhập địa chỉ email',
    EMPTY_INFOR: 'Bạn cần nhập đầy đủ thông tin đăng nhập.',
    WRONG_EMAIL: 'Địa chỉ email không hợp lệ',
    REGISTER_ACCOUNT: 'Đăng ký tài khoản',
    REGISTER_HERE: 'Đăng ký tài khoản',
    YOU_HAVE_NOT_ACCOUNT: 'Bạn chưa có tài khoản? ',
    LOGIN: 'Đăng nhập',
    LOGOUT: 'Đăng xuất',
    WELCOME: { TITLE: 'Chào mừng bạn đến với colorME', DESCRIPTION: 'Mời bạn trải nghiệm bản thử nghiệm của colorME App' },
    EMAIL_ALREADY_EXIST: 'Địa chỉ email đã tồn tại',
    USERNAME_ALREADY_EXIST: 'Tên người dùng đã tồn tại',
    NOTIFICATION_TITLE_HEADER: 'Thông báo',
    PROFILE_TITLE_HEADER: 'Hồ sơ',
    COURSE_TITLE_HEADER: 'Đăng kí học',
    NEWS_TITLE_HEADER: 'Bài viết',
    NEWS_DRAWER: 'Tin tức',
    HOME_DRAWER: 'Trang chủ',
    BASE_DRAWER: 'Cơ sở',
    GUIDE_DRAWER: 'Chỉ đường',
    SHARING_EXPERIENCES_TITLE_HEADER: 'Chia sẻ kinh nghiệm',
    DIRECT_HEADER_TITLEL: 'CHỈ ĐƯỜNG',
    NULL_DATA: 'Không có dữ liệu',
    UPDATE_INFORMATION: 'Cập nhập thông tin',
    SCHEDULE: 'Lịch học',
    UPDATING_INFORMATION: 'Đang cập nhập thông tin',
    STUDY: 'HỌC TẬP',
    PROCESS: 'Tiến độ',
    ATTENDANCE: 'Điểm danh',
    CALENDAR_STUDY: 'Lịch học',
    ACTION_ROOT_TAB_COURSE: 'ROOT_TAB_COURSE',
    ACTION_GO_DETAIL_COURSE: 'STUDY_REGISTER_DETAIL_COURSE',
    ACTION_CHOOSE_TAG_REGISTER_STUDY: 'STUDY_REGISTER_CHOOSE_TAG',   
    ACTION_CHOOSE_TAG_LEARNING: 'LEARNING_CHOOSE_TAG',    
    ACTION_ROOT_TAB_USER: 'ROOT_TAB_USER',
    ACTION_CHOOSE_TAG: 'FEED_CHOOSE_TAG',
    ACTION_ROOT_TAB_NOTIFICATION: 'ROOT_TAB_NOTIFICATION',
    ACTION_ROOT_TAB_STUDY: 'ACTION_ROOT_TAB_STUDY',
    ACTION_ROOT_TAB_HOME: 'ROOT_TAB_HOME',
    ACTION_LOGIN_LOGIN: 'LOGIN_ACTION_LOGIN',
    ACTION_REGISTER_REGISTER: 'REGISTER_ACTION_REGISTER',
    ACTION_GO_DETAIL_BLOG: 'FEED_BLOG_DETAIL_BLOG',
    ACTION_LOGIN_LOADED: 'LOGIN_LOADED',
    ACTION_REGISTER_LOADED: 'REGISTER_LOADED',
    ACTION_ROOT_DRAWER_SALE: 'ROOT_DRAWER_SALE',
    ACTION_ROOT_DRAWER_SOURCE: 'ROOT_DRAWER_SOURCE',
    ACTION_ROOT_DRAWER_GUIDE: 'ROOT_DRAWER_GUIDE',
    
    

}