export const STRINGS = {
    LOGO_COLOR: 'color',
    LOGO_ME: 'ME',
    REGISTER: 'Register',
    NAME: 'Name',
    EMAIL: 'Email',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    HAVE_ERROR: 'Có lỗi xảy ra',
    EMPTY_NAME: 'Bạn chưa nhập tên',
    EMPTY_USERNAME: 'Bạn chưa nhập tên tài khoản',
    EMPTY_PASSWORD: 'Bạn chưa nhập mật khẩu',
    EMPTY_EMAIL: 'Bạn chưa nhập địa chỉ email',
    WRONG_EMAIL: 'Địa chỉ email không hợp lệ',
    REGISTER_ACCOUNT: 'Đăng ký tài khoản',
    LOGIN: 'Đăng nhập',
    WELCOME: { TITLE: 'Chào mừng bạn đến với colorME', DESCRIPTION: 'Mời bản trải nghiệm bản thử nghiệm của colorME App' },
    EMAIL_ALREADY_EXIST: 'Địa chỉ email đã tồn tại',
    USERNAME_ALREADY_EXIST: 'Tên người dùng đã tồn tại',
    NOTIFICATION_TITLE_HEADER : 'Thông báo',
    PROFILE_TITLE_HEADER : 'Hồ sơ',
    COURSE_TITLE_HEADER: 'Khoá học',
    NEWS_TITLE_HEADER : 'TIN TỨC',
    SHARING_EXPERIENCES_TITLE_HEADER: 'Chia sẻ kinh nghiệm',
    BASE_HEADER_TITLEL: 'Cơ sở',
    NULL_DATA: 'Không có dữ liệu', 
    UPDATE_INFORMATION: 'Cập nhập thông tin',
}