# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'colorMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for colorMe
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'colorMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'colorMe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for colorMe-tvOS

  target 'colorMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
