import {Platform} from 'react-native';

export const none = 'transparent';
export const background = '#FFF';
export const gray = 'gray';
export const textColor = '#000000';
export const iconColor = '#000000';
export const mainColor  = '#c50000';
export const loadingImage = '#FFF';
export const themeColor = '#FFFFFF';
export const colorGradient0 = '#FFFFFF';
export const colorGradient1 = '#FFFFFF';
export const colorGradient2 = '#FFFFFF';
export const navTitle       = 'rgb(255,255,255)';
export const textColorNotActive = 'rgba(0, 0, 0, 0.2)';
export const textColorNotActive2 = 'rgba(255, 255, 255, 0.5)';
export const shadowColor = 'rgba(0,0,0,0.5)';
export const star = '#ffff05';
export const blueDashboard = '#4697E8';
export const buttonPlay = 'rgba(155, 141, 171, 0.4)';
export const buttonNext = 'rgba(255, 255, 255, 0.4)';
export const textColorReverse = '#FFFFFF';
export const blue = 'rgb(0, 128, 214)';
export const darkGray = 'rgb(109, 109,109)';
