export default {
    home:{
        isLoading: false,
        isLoadingMore: false,
        isLoadingSearch: false,
        isRefreshing : false,
        blogs: [],
    },
    blog:{
        isLoading: false,
        data: {},
    },
    book:{
        isLoading: false,
        isLoadingSearch: false,
        books: [],
        typeBooks: [],
        isLoadingMore : false,
        isRefreshing : false,
        isLoadingTypeBook : false,
        status : 0,
    },
    login: {
        login: {},
        loginStatus: false,
        token: null,
        isLoading: false,
        error: false,
        result: false,
        isGetLocalData: false,
        status: 0,
        user: {},
    },
    register: {
        register: {},
        isLoading: false,
        error: false,
        status: 0,
    },
    survey: {
        isLoading: false,
        isLoadingMoreSurvey: false,
        isRefreshingSurvey: false,
        isLoadingQuestion: false,
        isLoadingCloseSurvey: false,
        isLoadingMoreHistorySurvey: false,
        isRefreshingHistorySurvey: false,
        isLoadingAnswer: false,
        surveys: {},
        statusAnswer: 0,
        questions: {},
        lesson: {},
        historySurvey: [],
        isLoadingHistorySurvey: false,
    },
}